### PR TITLE
Apply prettier formatting and fix footer for NYBRI

### PR DESCRIPTION
**Pull request by YoungwooWatson**
**Issue Description:**
There was a noticeable gap between the main content section and the footer in rating.html, which was not consistent with the layout of other pages on the NYBRI website. Initial suspicion was that this gap might be related to the unique dropdown menu feature in rating.html.

**Attempted Fixes:**
Initial attempts to fix the issue involved CSS adjustments, such as modifying margin-top properties. However, these changes either did not resolve the issue or adversely affected the layout of the entire website. Given that CSS modifications did not yield satisfactory results and that the issue was isolated to rating.html (as other pages did not exhibit this problem), the focus shifted to examining the HTML structure.

**Resolution:**
Upon a detailed review and application of Prettier formatting in Visual Studio Code, it was discovered that the 'div class="footer row"' was incorrectly placed outside of 'div id="main" class="container"'. Adjusting the HTML structure to ensure that the footer div is a child of the container div resolved the layout issue, allowing the footer to behave as intended across different page states, including with and without the dropdown content expanded.

**Additional Changes:**
To prevent similar oversight in the future and ensure consistency across the NYBRI website, Prettier formatting was applied to all HTML documents associated with the site. This accounts for the extensive changes seen in the commit history, aiming to enhance code readability and maintainability.

**Request for Review:**
Please review the changes made in this pull request. Your feedback is invaluable, and I'm open to further discussions or clarifications if needed. Upon approval, I plan to merge these changes with the develop branch.

Thank you!

### CODE REVIEW

**Comment by jcoro001** [comment]
I think the changes look good, but it looks like there's some conflicts. It might be good to go over it with the team today during our meeting to make sure nothing is lost.

**Comment by c0demat1cs** [comment]
I don't remember exactly what the footer issue was but I agree with James, it looks good, and we should discuss possible conflicts today.

**Comment by c0demat1cs** [comment]
Oh and yes, Prettier formatting is the way to go.  I found similar issues on Lobbster and have had to move some tags around.

**Comment by YoungwooWatson** [comment]
New pull-request have been made

**Pull request closed without merging**
